name: PHP Linting
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'dependabot/npm_and_yarn/*'
jobs:
  phplint:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Pint CS Fixer
        uses: aglipanci/laravel-pint-action@v2
        with:
          verboseMode: true
          preset: psr12

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: PHP Linting (Pint)
          skip_fetch: true
