name: run-tests

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-latest]
                php: [8.0,8.1,8.2]
                laravel: [8.*,9.*,10.*,11.x-dev]
                stability: [prefer-stable]
                exclude:
                    # Exclude Laravel 9 with PHP 8.0
                    - laravel: 9.*
                      php: 8.0
                    - laravel: 10.*
                      php: 8.0
                    - laravel: 11.x-dev
                      php: 8.0
                    - laravel: 11.x-dev
                      php: 8.1

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
                  coverage: none

            - name: Setup problem matchers
              run: |
                  echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                  echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
                  composer update --${{ matrix.stability }} --prefer-dist --no-interaction
            - name: Execute tests
              run: vendor/bin/phpunit
